POST   http://localhost:3333/find-place?lat=45&lng=-110
Content-Type: application/json

### authenticate a driver
POST   http://localhost:3333/driver/authenticate
Content-Type: application/json

{
  "email":"anaclara51@live.com",
  "password": "e7B9AXuGq3"
}



    