POST   http://localhost:3333/find-place?lat=45&lng=-110
Content-Type: application/json

### authenticate a driver
POST   http://localhost:3333/driver/authenticate
Content-Type: application/json

{
  "email":"anaclara51@live.com",
  "password": "e7B9AXuGq3"
}



### update driver status
POST   http://localhost:3333/manager/driver/update-status
Content-Type: application/json

 {
   "status":"On",
   "id": "b6122cbd-f290-4c41-8fff-f765c9fba9c8"
 }


    
